package com.hr.api;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.hibernate.validator.constraints.Length;

import java.time.LocalDate;

/**
 * Created by hendersonra on 07/10/16.
 */
public class Employee {

    private long employeeNumber;

    private LocalDate dateOfBirth;

    @Length(max = 14)
    private String firstName;

    @Length(max = 16)
    private String lastName;

    @Length(max = 1)
    private String gender;

    private LocalDate hireDate;

    @JsonCreator
    public Employee(@JsonProperty("employeeNumber") long employeeNumber,
                    @JsonProperty("dateOfBirth") LocalDate dateOfBirth,
                    @JsonProperty("firstName") String firstName,
                    @JsonProperty("lastName") String lastName,
                    @JsonProperty("gender") String gender,
                    @JsonProperty("hireDate") LocalDate hireDate) {
        this.employeeNumber = employeeNumber;
        this.dateOfBirth = dateOfBirth;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.hireDate = hireDate;
    }

    @JsonProperty
    public long getEmployeeNumber() {
        return employeeNumber;
    }

    @JsonProperty
    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    @JsonProperty
    public String getFirstName() {
        return firstName;
    }

    @JsonProperty
    public String getLastName() {
        return lastName;
    }

    @JsonProperty
    public String getGender() {
        return gender;
    }

    @JsonProperty
    public LocalDate getHireDate() {
        return hireDate;
    }

    @Override
    public boolean equals(Object obj) {
        return obj != null &&
                obj.getClass().equals(this.getClass()) &&
                ((Employee) obj).getEmployeeNumber() == this.getEmployeeNumber() &&
                ((Employee) obj).getDateOfBirth().equals(this.getDateOfBirth()) &&
                ((Employee) obj).getFirstName().equals(this.getFirstName()) &&
                ((Employee) obj).getLastName().equals(this.getLastName()) &&
                ((Employee) obj).getGender().equals(this.getGender()) &&
                ((Employee) obj).getHireDate().equals(this.getHireDate());
    }

    // Generated by Intellij
    @Override
    public int hashCode() {
        int result = (int) (employeeNumber ^ (employeeNumber >>> 32));
        result = 31 * result + dateOfBirth.hashCode();
        result = 31 * result + firstName.hashCode();
        result = 31 * result + lastName.hashCode();
        result = 31 * result + gender.hashCode();
        result = 31 * result + hireDate.hashCode();
        return result;
    }
}
