package com.hr.api;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;

/**
 * Created by hendersonra on 10/10/16.
 */
public class Salary {

    private long salary;
    private LocalDate from;
    private  LocalDate to;

    @JsonCreator
    public Salary(@JsonProperty("salary") long salary,
                  @JsonProperty("from") LocalDate from,
                  @JsonProperty("to") LocalDate to) {
        this.salary = salary;
        this.from = from;
        this.to = to;
    }

    @JsonProperty
    public long getSalary() {
        return salary;
    }

    @JsonProperty
    public LocalDate getFrom() {
        return from;
    }

    @JsonProperty
    public LocalDate getTo() {
        return to;
    }

    // Generated by Intellij
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Salary salary1 = (Salary) o;

        if (salary != salary1.salary) return false;
        if (!from.equals(salary1.from)) return false;
        return to.equals(salary1.to);

    }

    // Generated by Intellij
    @Override
    public int hashCode() {
        int result = (int) (salary ^ (salary >>> 32));
        result = 31 * result + from.hashCode();
        result = 31 * result + to.hashCode();
        return result;
    }
}
