package com.hr.api;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;

/**
 * Created by hendersonra on 10/10/16.
 */
public class Title {

    private String title;
    private LocalDate from;
    private LocalDate to;

    @JsonCreator
    public Title(@JsonProperty("title") String title,
                 @JsonProperty("from") LocalDate from,
                 @JsonProperty("to") LocalDate to) {
        this.title = title;
        this.from = from;
        this.to = to;
    }

    @JsonProperty
    public String getTitle() {
        return title;
    }

    @JsonProperty
    public LocalDate getFrom() {
        return from;
    }

    @JsonProperty
    public LocalDate getTo() {
        return to;
    }

    // Generated by Intellij
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Title title1 = (Title) o;

        if (!title.equals(title1.title)) return false;
        if (!from.equals(title1.from)) return false;
        return to.equals(title1.to);

    }

    // Generated by Intellij
    @Override
    public int hashCode() {
        int result = title.hashCode();
        result = 31 * result + from.hashCode();
        result = 31 * result + to.hashCode();
        return result;
    }
}
